### ISSUE TITLE
请问如何监听Tag的点击事件啊

### ISSUE THREAD

**Issue by jinfei-lab** [haiweilian/taggd-manager#10]

**Comment by haiweilian** [comment]
配置对象的 show 和 hide 的选项为 click 是否可以满足你的需求。

或许我想你的需求只是单纯需要监听的 tag 的点击事件，那么现在是没有这个事件的回调。我现在外地没条件修改，如果你现在急需可以拉取源码稍加修改然后提交 PR。

**Comment by jinfei-lab** [comment]
> 配置对象的 show 和 hide 的选项为 click 是否可以满足你的需求。
> 
> 或许我想你的需求只是单纯需要监听的 tag 的点击事件，那么现在是没有这个事件的回调。我现在外地没条件修改，如果你现在急需可以拉取源码稍加修改然后提交 PR。

好的,多谢,我试一试

**Comment by Blizzard-liu** [comment]
你搞出来没有 大佬们

**Comment by jinfei-lab** [comment]
> 你搞出来没有 大佬们

我用曲线救国的方法临时实现了

**Comment by Blizzard-liu** [comment]
我也搞好了  跟不上需求了快

**Comment by jinfei-lab** [comment]
> 我也搞好了 跟不上需求了快

我给tag实例加了个点击事件的监听

**Comment by Blizzard-liu** [comment]
我打包之后  竟然显示空白 也没报错 你有遇到过吗
