### ISSUE TITLE
大佬 有没有遇到一个问题 tag拖动完成后 整个页面刷新了 vue写的  

### ISSUE THREAD

**Issue by Blizzard-liu** [haiweilian/taggd-manager#12]

**Comment by haiweilian** [comment]
可否提供一个复现的例子。

**Comment by Blizzard-liu** [comment]
https://github.com/Blizzard-liu/vue-base

大佬 我把代码放在这个项目了 点击tagged按钮即可复现

**Comment by haiweilian** [comment]
内部使用的 `button` 标签影响 `element-ui` 的 `el-form` 的默认行为了，可以先加上 `@submit.native.prevent` 可立即解决，我再想想要不要从内部解决。

```vue
<el-form @submit.native.prevent />
```

**Comment by Blizzard-liu** [comment]
大佬真乃神人也  昨天想了一天都没头绪  受小弟一拜
