### ISSUE TITLE
大佬   背景图片可以拖到可视窗口的外面   这样就看不到了  这个情况怎么限制啊

### ISSUE THREAD

**Issue by Blizzard-liu** [haiweilian/taggd-manager#13]

**Comment by haiweilian** [comment]
我是先想到锁边功能，只能在容器内拖动，但这样会影响缩放和移动的灵活性，其实没必要限制这块。所以只解决因为拖到可视窗口之外并且图片完全不可见时，如果此时松开鼠标将恢复到上次开始拖动的位置。

**Comment by haiweilian** [comment]
修复 #13、#14 发布在 [v/1.1.1](https://www.npmjs.com/package/taggd-manager/v/1.1.1)

**Comment by Blizzard-liu** [comment]
大佬  666 所向无敌啊
