### ISSUE TITLE
大佬 建议增加tag的点击事件啊

### ISSUE THREAD

**Issue by Blizzard-liu** [haiweilian/taggd-manager#19]

**Comment by haiweilian** [comment]
好啊，可以先用下面的方法代替。但是 `mouseup` 和 `click` 事件冲突，也就是拖拽的时候也会触发 `click`，下班了我会在内部处理试试，外部处理 -> www.baidu.com

```js
var tag = new Taggd.Tag()
tag.buttonElement.addEventListener('click', () => {
     console.log(tag)
})
```

**Comment by Blizzard-liu** [comment]
大佬 666啊 在哪上班  你要是女的 我就追你了

**Comment by Blizzard-liu** [comment]
大佬  我打包之后 竟然显示空白 也没报错 这是啥情况

**Comment by haiweilian** [comment]
> 大佬 我打包之后 竟然显示空白 也没报错 这是啥情况

我跑下昨天的示例试试，我这坑是填不完了 [旺柴][旺柴]。

**Comment by Blizzard-liu** [comment]
我把依赖包下载到本地  再打包还是不行   最后一坑

**Comment by Blizzard-liu** [comment]
大佬 别看了 我滴锅

**Comment by Blizzard-liu** [comment]
大佬 别看了 我滴锅

**Comment by Blizzard-liu** [comment]
大佬 别看了 我滴锅

**Comment by haiweilian** [comment]
我刚也跑了是好的。今天把留的坑都填填，你这几波提的问题把插件完善了很多啊，给力。我当初的需求很简单的。
