### ISSUE TITLE
improving behavior of tagg.destroy()

### ISSUE THREAD

**Issue by fuweichin** [haiweilian/taggd-manager#3]
Expect `tagg.destroy()` to do more:

+ to remove all event listeners taggd added to the `img`
+ to restore all style changes taggd made to the `img`  (need to take a snapshot on img.style.cssText during intialization)
+ to put `img` to its original position in DOM tree (e.g. by replacing `div.taggd__wrapper` with the `img`)

thus the `img` can be reused to load another photo to create a new Tagg instance.

Currently I use workaround to get over it.

**Comment by haiweilian** [comment]
Thanks for your feedback, It does need.
