### ISSUE TITLE
新增的标记支持使用自定义的图片吗？

### ISSUE THREAD

**Issue by Camelliaguoqian** [haiweilian/taggd-manager#9]
你好，新增标记时，如果想设置标记为不同的小图片，有这种类似的功能吗？

**Comment by Camelliaguoqian** [comment]
也可以实现的。先修改下.taggd__button的背景图片样式，然后在new Taggd.Tag()的第3个入参可以传对应的class

**Comment by Blizzard-liu** [comment]
大佬  求代码

**Comment by Blizzard-liu** [comment]
大佬  有没有遇到一个问题  tag拖动完成后 整个页面刷新了 vue写的
